name: CI/CD for React App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUCKET: react-app-on-aws-7-22-2025
      DIST: build
      REGION: us-east-1
      DIST_ID: E3BFL2AN2U7IV2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install 

      - name: Build the app
        run: npm run build

      - name: Copy files to the production website with the AWS CLI
        run: | 
          aws s3 sync --delete ${{ env.DIST }} s3://${{ env.BUCKET }}

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \ 
          --distribution-id ${{ env.DIST_ID }} \
          --paths "/*"

     
